title: "Akka"

baseurl: ""

markdown: kramdown

sass: 
  sass_dir: resources/stylesheets
  style: compressed

exclude:
- README

defaults:
-
  scope:
    path: "" # all files
  values: # note that changing this requires a jekyll restart to be picked up if serving locally
    current_akka_version: 2.4.17
    current_akka_http_version: 10.0.4
    current_java_scala_version: 2.11 # used for deps for Java
